# Generated by Django 4.0.4 on 2022-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('paper_url', models.CharField(max_length=1000)),
                ('published_date', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('updated', models.CharField(max_length=250)),
                ('pdf_url', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
    ]
