# Generated by Django 4.0.4 on 2022-07-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinearAlgebra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=1000)),
            ],
        ),
    ]
