# Generated by Django 4.0.4 on 2022-07-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0002_linearalgebra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearalgebra',
            name='expression',
            field=models.TextField(),
        ),
    ]
